[package]
name = "flowquad"
description = "Flowquad is a library that helps you build UI stuff with Macroquad."
license = "MIT"
repository = "https://github.com/Muhtasim-Rasheed/flowquad"
version = "1.0.0"
edition = "2024"

[dependencies]
macroquad = "0.4.14"
